#!/bin/sh
set -x
set -e

for filediag in DIAG_gen.nam 

do

cp $filediag DIAG1.nam

export MPIRUN="mpirun -np 1 " 

time ${MPIRUN} DIAG${XYZ}

sed -i 's/DACC7.1.AERON.002/DACC7.1.AERON.003/g' DIAG1.nam
pwd
time ${MPIRUN} DIAG${XYZ}

sed -i 's/DACC7.1.AERON.003/DACC7.1.AERON.004/g' DIAG1.nam
pwd
time ${MPIRUN} DIAG${XYZ}

sed -i 's/DACC7.1.AERON.004/DACC7.1.AERON.002/g' DIAG1.nam
done
