#!/bin/sh
set -x
set -e

for filediag in DIAG_gen.nam 

do

cp $filediag DIAG1.nam

export MPIRUN="mpirun -np 1 " 

time ${MPIRUN} DIAG${XYZ}

sed -i 's/CLEA4.1.AEROF.001/CLEA4.1.AEROF.002/g' DIAG1.nam
pwd
time ${MPIRUN} DIAG${XYZ}

sed -i 's/CLEA4.1.AEROF.002/CLEA4.1.AEROF.003/g' DIAG1.nam
pwd
time ${MPIRUN} DIAG${XYZ}

sed -i 's/CLEA4.1.AEROF.003/CLEA4.1.AEROF.004/g' DIAG1.nam
pwd
time ${MPIRUN} DIAG${XYZ}

sed -i 's/CLEA4.1.AEROF.004/CLEA4.1.AEROF.001/g' DIAG1.nam
done

